name: PR checks
on:
  pull_request:
    branches:
      - master
jobs:
  Run-CI-Script:
    runs-on: [self-hosted, medium, amd64]
    steps:
      - uses: actions/checkout@v2
      - run: scripts/ci.sh
